### ISSUE TITLE
Spec tests are failing due to facter version

### ISSUE THREAD

**Issue by rgardner4012** [simp/pupmod-simp-simplib#279]
An error occurred while loading ./spec/functions/simplib/simp_version_spec.rb.
Failure/Error: 
    on_supported_os.each do |os, os_facts|
      context "on #{os}" do
        let(:facts){ os_facts }
  
        let(:simp_version_path) {
          if os_facts[:kernel].casecmp?('windows')
            'C:\ProgramData\SIMP\simp.version'
          else
            '/etc/simp/simp.version'
          end

RuntimeError:
  Can't find SIMP facts for Facter 4.3, skipping...

  HINT: If this version of Facter has been released recently, try running

      `FACTER_GEM_VERSION='~> X.Y.0' bundler update facter

  Where 'X.Y' is the version of the last facter that worked
# ./spec/functions/simplib/simp_version_spec.rb:5:in `block in <top (required)>'
# ./spec/functions/simplib/simp_version_spec.rb:4:in `<top (required)>'

1 deprecation warning total

Finished in 0.00006 seconds (files took 1.61 seconds to load)
0 examples, 0 failures, 3 errors occurred outside of examples

/opt/hostedtoolcache/Ruby/2.7.7/x64/bin/ruby -I/home/runner/work/pupmod-simp-simplib/pupmod-simp-simplib/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.1/lib:/home/runner/work/pupmod-simp-simplib/pupmod-simp-simplib/vendor/bundle/ruby/2.7.0/gems/rspec-support-3.12.0/lib /home/runner/work/pupmod-simp-simplib/pupmod-simp-simplib/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.12.1/exe/rspec --pattern spec/\{aliases,classes,defines,functions,hosts,integration,plans,tasks,type_aliases,types,unit\}/\*\*/\*_spec.rb failed

**Comment by AndyAdrian-OP** [comment]
fixed by https://github.com/simp/rubygem-simp-rspec-puppet-facts/pull/47
